version: "3.9"
services:
  backend:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - DATABASE_URL=postgresql://awesh:welcome123@localhost:5432/mydb?schema=public
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=awesh
      - POSTGRES_PASSWORD=welcome123
      - POSTGRES_DB=mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
